version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          - yarn-packages-
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test